// Category / theme taxonomy: a clickable symbol layer that sits alongside
// `type` (src/_data/symbols.js). A note's `type` is what it *is* (quote,
// diary, snippet...); its `themes` (see frontmatter schema in
// docs/instructions.md) are what it's *about*, drawn from this list.
//
// Two symbol families, purely for visual variety and to keep the taxonomy
// from running out of distinct glyphs: the 12 zodiac symbols for broad
// subject themes, and the 9 classical planetary symbols for technology
// subcategories. `color` maps to the `--nav-*` custom properties in
// src/assets/css/style.css.
export default {
  aries: {
    slug: "aries",
    symbol: "♈︎",
    label: "Technology & Web",
    description: "Web development, internet culture, digital tools",
    color: "nav-red",
    group: "zodiac",
  },
  taurus: {
    slug: "taurus",
    symbol: "♉︎",
    label: "Social Justice & Politics",
    description: "Political analysis, social movements, justice issues",
    color: "nav-orange",
    group: "zodiac",
  },
  gemini: {
    slug: "gemini",
    symbol: "♊︎",
    label: "Arts & Culture",
    description: "Literature, music, visual arts, cultural criticism",
    color: "nav-yellow",
    group: "zodiac",
  },
  cancer: {
    slug: "cancer",
    symbol: "♋︎",
    label: "Philosophy & Ideas",
    description: "Philosophical concepts, theoretical frameworks",
    color: "nav-green",
    group: "zodiac",
  },
  leo: {
    slug: "leo",
    symbol: "♌︎",
    label: "Personal Development",
    description: "Self-improvement, mental health, wellness",
    color: "nav-blue",
    group: "zodiac",
  },
  virgo: {
    slug: "virgo",
    symbol: "♍︎",
    label: "Science & Research",
    description: "Academic research, scientific studies, data",
    color: "nav-purple",
    group: "zodiac",
  },
  libra: {
    slug: "libra",
    symbol: "♎︎",
    label: "Writing Craft",
    description: "Writing techniques, creative process, publishing",
    color: "nav-magenta",
    group: "zodiac",
  },
  scorpio: {
    slug: "scorpio",
    symbol: "♏︎",
    label: "Education & Learning",
    description:
      "Education, teaching, tutorials, documentation, libraries, learning resources",
    color: "nav-red",
    group: "zodiac",
  },
  sagittarius: {
    slug: "sagittarius",
    symbol: "♐︎",
    label: "Productivity",
    description: "Productivity systems, workflows, organization",
    color: "nav-orange",
    group: "zodiac",
  },
  capricorn: {
    slug: "capricorn",
    symbol: "♑︎",
    label: "System Tools",
    description: "Operating systems, utilities, infrastructure",
    color: "nav-yellow",
    group: "zodiac",
  },
  aquarius: {
    slug: "aquarius",
    symbol: "♒︎",
    label: "Community & Social",
    description: "Communities, social platforms, mutual aid",
    color: "nav-green",
    group: "zodiac",
  },
  pisces: {
    slug: "pisces",
    symbol: "♓︎",
    label: "Mental Health & Wellness",
    description: "Psychology, therapy, emotional well-being",
    color: "nav-blue",
    group: "zodiac",
  },
  moon: {
    slug: "moon",
    symbol: "☽︎",
    label: "Web Infrastructure & Hosting",
    description: "Hosting platforms, CDNs, domains, DNS, web servers, deployment",
    color: "nav-gray",
    group: "planet",
  },
  mercury: {
    slug: "mercury",
    symbol: "☿︎",
    label: "APIs & Integration",
    description: "APIs, webhooks, integrations, microservices, data exchange",
    color: "nav-red",
    group: "planet",
  },
  venus: {
    slug: "venus",
    symbol: "♀︎",
    label: "Design & UX",
    description: "UI/UX design, CSS, accessibility, visual design, user experience",
    color: "nav-orange",
    group: "planet",
  },
  mars: {
    slug: "mars",
    symbol: "♂︎",
    label: "Security & Privacy",
    description: "Encryption, security tools, privacy, authentication, cybersecurity",
    color: "nav-yellow",
    group: "planet",
  },
  jupiter: {
    slug: "jupiter",
    symbol: "♃︎",
    label: "Large Platforms & Services",
    description: "Major platforms (GitHub, GitLab), social networks, large-scale services",
    color: "nav-green",
    group: "planet",
  },
  saturn: {
    slug: "saturn",
    symbol: "♄︎",
    label: "Legacy Systems & Maintenance",
    description: "Legacy code, maintenance, refactoring, technical debt, system updates",
    color: "nav-blue",
    group: "planet",
  },
  uranus: {
    slug: "uranus",
    symbol: "♅︎",
    label: "Emerging Tech & Innovation",
    description: "AI, machine learning, blockchain, Web3, emerging technologies",
    color: "nav-purple",
    group: "planet",
  },
  neptune: {
    slug: "neptune",
    symbol: "♆︎",
    label: "Data & Analytics",
    description: "Data science, analytics, databases, statistics, data visualization",
    color: "nav-magenta",
    group: "planet",
  },
  pluto: {
    slug: "pluto",
    symbol: "♇︎",
    label: "Infrastructure & DevOps",
    description: "DevOps, CI/CD, infrastructure, containers, orchestration, automation",
    color: "nav-red",
    group: "planet",
  },
};
